
#Respostas

#Questão 01

SELECT
	CAN.NOME_CANTOR AS NOME_CANTOR,
	COUNT(GCAO.COD_CANTOR) AS NUM_GRAVACOES
FROM
	DML.GRAVACAO GCAO
INNER JOIN DML.CANTOR CAN ON
	GCAO.COD_CANTOR = CAN.COD_CANTOR
GROUP BY
	GCAO.COD_CANTOR
HAVING
	NUM_GRAVACOES = (
		SELECT
			MIN(MINGRAVACOES.COUNTGRAVACOES)
		FROM	(
			SELECT
				COD_CANTOR, 
				COUNT(COD_CANTOR) AS COUNTGRAVACOES
			FROM
				DML.GRAVACAO
			GROUP BY
				COD_CANTOR 
		) MINGRAVACOES 
	);


#Questão 02

SELECT
	CAN.NOME_CANTOR AS NOME_CANTOR,
	COUNT(DISTINCT(GCAO.COD_GRAVADORA)) AS NUM_GRAVACOES
FROM
	DML.GRAVACAO GCAO
INNER JOIN DML.CANTOR CAN ON
	GCAO.COD_CANTOR = CAN.COD_CANTOR
GROUP BY
	GCAO.COD_CANTOR
HAVING
	NUM_GRAVACOES = (
		SELECT
			MAX(SUB1.GRAV)
		FROM
			DML.CANTOR CAN
		INNER JOIN (
			SELECT
				COD_CANTOR, 
				COUNT(DISTINCT(COD_GRAVADORA)) AS GRAV
			FROM
				DML.GRAVACAO
			GROUP BY
				COD_CANTOR 
		) SUB1 ON
		CAN.COD_CANTOR = SUB1.COD_CANTOR 
	)
ORDER BY NOME_CANTOR;


#Questão 03

SELECT
	SUB.NOME_CANTOR AS NOME_CANTOR,
	MAX(SUB.MEDIA) AS MEDIA
FROM
(
	SELECT
		CAN.NOME_CANTOR, 
		AVG(MUS.DURACAO) MEDIA
	FROM
		DML.GRAVACAO GCAO
	INNER JOIN DML.MUSICA MUS ON
		GCAO.COD_MUSICA = MUS.COD_MUSICA
	INNER JOIN DML.CANTOR CAN ON
		GCAO.COD_CANTOR = CAN.COD_CANTOR
	GROUP BY
		CAN.NOME_CANTOR
	ORDER BY
		MEDIA DESC 
) SUB;


#Questão 04

SELECT
	CAN.NOME_CANTOR AS NOME_CANTOR
FROM
	DML.CANTOR CAN
WHERE
	NOT EXISTS (
		SELECT
			*
		FROM
			DML.GRAVACAO GCAO
		INNER JOIN DML.GRAVADORA GRAV ON
			GCAO.COD_GRAVADORA = GRAV.COD_GRAVADORA
		WHERE
			GCAO.COD_CANTOR = CAN.COD_CANTOR
			AND GRAV.NOME_GRAVADORA = 'Sony' 
);


#Questão 05

SELECT
	CAN.NOME_CANTOR AS CANTOR,
	MUS.TITULO AS MUSICA,
	GCAO.DATA_GRAVACAO AS DATA_GRAVACAO
FROM
	DML.GRAVACAO GCAO
INNER JOIN DML.MUSICA MUS ON
	GCAO.COD_MUSICA = MUS.COD_MUSICA
INNER JOIN DML.CANTOR CAN ON
	GCAO.COD_CANTOR = CAN.COD_CANTOR
WHERE
	YEAR(GCAO.DATA_GRAVACAO) = '2004';


#Questão 06

SELECT
	CAN.NOME_CANTOR AS CANTOR,
	MAX(GCAO.DATA_GRAVACAO) AS DATA_ULTIMA_GRAVACAO
FROM
	DML.CANTOR CAN
LEFT JOIN DML.GRAVACAO GCAO ON
	GCAO.COD_CANTOR = CAN.COD_CANTOR
GROUP BY
	CAN.NOME_CANTOR
ORDER BY
	DATA_ULTIMA_GRAVACAO DESC;



#Questão 07

SELECT
	P.NOME_PESSOA AS NOME,
	FR.NUMERO AS FONE_RESIDENCIAL,
	FC.NUMERO AS FONE_COMERCIAL,
	FL.NUMERO AS CELULAR 
FROM
	DML.PESSOA P
INNER JOIN DML.FONE FR ON
	P.COD_PESSOA = FR.COD_PESSOA
	AND FR.TIPO = 'R'
INNER JOIN DML.FONE FC ON
	P.COD_PESSOA = FC.COD_PESSOA
	AND FC.TIPO = 'C'
INNER JOIN DML.FONE FL ON
	P.COD_PESSOA = FL.COD_PESSOA
	AND FL.TIPO = 'L';

